# render.yaml
services:
  - type: web
    name: cameroon-legal-assistant
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://huggingface.co/spaces/Ngum/cameroon-legal-assistant-api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        