# render.yaml
services:
  - type: web
    name: cameroon-legal-assistant
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist  # Use dist instead of build for Vite
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-username-cameroon-legal-assistant-api.hf.space
