# render.yaml
services:
  - type: web
    name: cameroon-legal-assistant
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist  # Updated path
    envVars:
      - key: VITE_API_URL  # Updated for Vite
        value: https://huggingface.co/spaces/ngum12/cameroon-legal-assistant-api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
